name: Remote SSH command
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Run Bash Script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          eval "$(ssh-agent -s)"
          ssh-add .ssh/github-deploy-key
          cd ez-invoice

          git restore .
          git checkout dev
          git pull

          sudo docker-compose down
          sudo docker-compose up -d --no-deps --build